# Generated by Django 4.1.7 on 2023-04-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_category_slug_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
