# Generated by Django 4.1.7 on 2023-04-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
    ]
