# Generated by Django 4.1.7 on 2023-04-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_user_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_liked',
        ),
    ]
