# Generated by Django 4.1.7 on 2023-04-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_user_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
