# Generated by Django 4.1.7 on 2023-04-09 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_alter_post_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
