# Generated by Django 4.1.7 on 2023-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_post_created_by_post_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
