# Generated by Django 4.1.7 on 2023-04-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_liked_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liked_posts',
            new_name='Liked_post',
        ),
    ]
