# Generated by Django 4.1.7 on 2023-04-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_liked_posts_liked_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked_post',
            name='likedby',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
