# Generated by Django 4.1.7 on 2023-04-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_followings',
        ),
    ]
