# Generated by Django 4.1.7 on 2023-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_post_likes'),
        ('accounts', '0014_remove_profile_total_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.post'),
        ),
    ]
