# Generated by Django 4.1.7 on 2023-04-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='none', max_length=200, null=True, unique=True),
        ),
    ]
