# Generated by Django 4.1.7 on 2023-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_post_slug'),
        ('accounts', '0019_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='posts.post'),
        ),
    ]
